include: package:lint/analysis_options.yaml

analyzer:
  errors:
    missing_return: error
    missing_required_param: error
    must_be_immutable: error
    sort_unnamed_constructors_first: ignore
    sized_box_for_whitespace: ignore
    sort_pub_dependencies: ignore

  exclude:
    - "**.*.g.dart"
    - "**.*.gr.dart"
    - "**.*.freezed.dart"